//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationConfiguration) DeepCopyInto(out *AuthorizationConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationConfiguration.
func (in *AuthorizationConfiguration) DeepCopy() *AuthorizationConfiguration {
	if in == nil {
		return nil
	}
	out := new(AuthorizationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationConfigurationList) DeepCopyInto(out *AuthorizationConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthorizationConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationConfigurationList.
func (in *AuthorizationConfigurationList) DeepCopy() *AuthorizationConfigurationList {
	if in == nil {
		return nil
	}
	out := new(AuthorizationConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationConfigurationObservation) DeepCopyInto(out *AuthorizationConfigurationObservation) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]KeyValue, len(*in))
		copy(*out, *in)
	}
	out.Links = in.Links
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationConfigurationObservation.
func (in *AuthorizationConfigurationObservation) DeepCopy() *AuthorizationConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(AuthorizationConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationConfigurationParameters) DeepCopyInto(out *AuthorizationConfigurationParameters) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]KeyValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationConfigurationParameters.
func (in *AuthorizationConfigurationParameters) DeepCopy() *AuthorizationConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(AuthorizationConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationConfigurationSpec) DeepCopyInto(out *AuthorizationConfigurationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationConfigurationSpec.
func (in *AuthorizationConfigurationSpec) DeepCopy() *AuthorizationConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(AuthorizationConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationConfigurationStatus) DeepCopyInto(out *AuthorizationConfigurationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationConfigurationStatus.
func (in *AuthorizationConfigurationStatus) DeepCopy() *AuthorizationConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(AuthorizationConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeySelector) DeepCopyInto(out *ConfigMapKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeySelector.
func (in *ConfigMapKeySelector) DeepCopy() *ConfigMapKeySelector {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigProperty) DeepCopyInto(out *ConfigProperty) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigProperty.
func (in *ConfigProperty) DeepCopy() *ConfigProperty {
	if in == nil {
		return nil
	}
	out := new(ConfigProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticAgentProfile) DeepCopyInto(out *ElasticAgentProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticAgentProfile.
func (in *ElasticAgentProfile) DeepCopy() *ElasticAgentProfile {
	if in == nil {
		return nil
	}
	out := new(ElasticAgentProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticAgentProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticAgentProfileList) DeepCopyInto(out *ElasticAgentProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticAgentProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticAgentProfileList.
func (in *ElasticAgentProfileList) DeepCopy() *ElasticAgentProfileList {
	if in == nil {
		return nil
	}
	out := new(ElasticAgentProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticAgentProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticAgentProfileObservation) DeepCopyInto(out *ElasticAgentProfileObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticAgentProfileObservation.
func (in *ElasticAgentProfileObservation) DeepCopy() *ElasticAgentProfileObservation {
	if in == nil {
		return nil
	}
	out := new(ElasticAgentProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticAgentProfileParameters) DeepCopyInto(out *ElasticAgentProfileParameters) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]ConfigProperty, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticAgentProfileParameters.
func (in *ElasticAgentProfileParameters) DeepCopy() *ElasticAgentProfileParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticAgentProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticAgentProfileSpec) DeepCopyInto(out *ElasticAgentProfileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticAgentProfileSpec.
func (in *ElasticAgentProfileSpec) DeepCopy() *ElasticAgentProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticAgentProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticAgentProfileStatus) DeepCopyInto(out *ElasticAgentProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	if in.AtProvider != nil {
		in, out := &in.AtProvider, &out.AtProvider
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticAgentProfileStatus.
func (in *ElasticAgentProfileStatus) DeepCopy() *ElasticAgentProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticAgentProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityLinks) DeepCopyInto(out *EntityLinks) {
	*out = *in
	out.Self = in.Self
	out.Doc = in.Doc
	out.Find = in.Find
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityLinks.
func (in *EntityLinks) DeepCopy() *EntityLinks {
	if in == nil {
		return nil
	}
	out := new(EntityLinks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentVariable) DeepCopyInto(out *EnvironmentVariable) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ValueSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariable.
func (in *EnvironmentVariable) DeepCopy() *EnvironmentVariable {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Filter) DeepCopyInto(out *Filter) {
	*out = *in
	if in.Ignore != nil {
		in, out := &in.Ignore, &out.Ignore
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Includes != nil {
		in, out := &in.Includes, &out.Includes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Filter.
func (in *Filter) DeepCopy() *Filter {
	if in == nil {
		return nil
	}
	out := new(Filter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Job) DeepCopyInto(out *Job) {
	*out = *in
	out.RunInstanceCount = in.RunInstanceCount
	out.Timeout = in.Timeout
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = make([]EnvironmentVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]TaskWithCancel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tabs != nil {
		in, out := &in.Tabs, &out.Tabs
		*out = make([]JobTab, len(*in))
		copy(*out, *in)
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]JobArtifact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Job.
func (in *Job) DeepCopy() *Job {
	if in == nil {
		return nil
	}
	out := new(Job)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobArtifact) DeepCopyInto(out *JobArtifact) {
	*out = *in
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(string)
		**out = **in
	}
	if in.StoreID != nil {
		in, out := &in.StoreID, &out.StoreID
		*out = new(string)
		**out = **in
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = make([]KeyValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobArtifact.
func (in *JobArtifact) DeepCopy() *JobArtifact {
	if in == nil {
		return nil
	}
	out := new(JobArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobTab) DeepCopyInto(out *JobTab) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobTab.
func (in *JobTab) DeepCopy() *JobTab {
	if in == nil {
		return nil
	}
	out := new(JobTab)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyValue) DeepCopyInto(out *KeyValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyValue.
func (in *KeyValue) DeepCopy() *KeyValue {
	if in == nil {
		return nil
	}
	out := new(KeyValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Link) DeepCopyInto(out *Link) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Link.
func (in *Link) DeepCopy() *Link {
	if in == nil {
		return nil
	}
	out := new(Link)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Material) DeepCopyInto(out *Material) {
	*out = *in
	if in.GitAttributes != nil {
		in, out := &in.GitAttributes, &out.GitAttributes
		*out = new(MaterialAttributesGit)
		(*in).DeepCopyInto(*out)
	}
	if in.SvnAttributes != nil {
		in, out := &in.SvnAttributes, &out.SvnAttributes
		*out = new(MaterialAttributesSvn)
		(*in).DeepCopyInto(*out)
	}
	if in.HgAttributes != nil {
		in, out := &in.HgAttributes, &out.HgAttributes
		*out = new(MaterialAttributesHg)
		(*in).DeepCopyInto(*out)
	}
	if in.P4Attributes != nil {
		in, out := &in.P4Attributes, &out.P4Attributes
		*out = new(MaterialAttributesP4)
		(*in).DeepCopyInto(*out)
	}
	if in.TfsAttributes != nil {
		in, out := &in.TfsAttributes, &out.TfsAttributes
		*out = new(MaterialAttributesTfs)
		(*in).DeepCopyInto(*out)
	}
	if in.DependencyAttributes != nil {
		in, out := &in.DependencyAttributes, &out.DependencyAttributes
		*out = new(MaterialAttributesDependency)
		**out = **in
	}
	if in.PackageAttributes != nil {
		in, out := &in.PackageAttributes, &out.PackageAttributes
		*out = new(MaterialAttributesPackage)
		(*in).DeepCopyInto(*out)
	}
	if in.PluginAttributes != nil {
		in, out := &in.PluginAttributes, &out.PluginAttributes
		*out = new(MaterialAttributesPlugin)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Material.
func (in *Material) DeepCopy() *Material {
	if in == nil {
		return nil
	}
	out := new(Material)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaterialAttributesDependency) DeepCopyInto(out *MaterialAttributesDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaterialAttributesDependency.
func (in *MaterialAttributesDependency) DeepCopy() *MaterialAttributesDependency {
	if in == nil {
		return nil
	}
	out := new(MaterialAttributesDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaterialAttributesGit) DeepCopyInto(out *MaterialAttributesGit) {
	*out = *in
	in.Filter.DeepCopyInto(&out.Filter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaterialAttributesGit.
func (in *MaterialAttributesGit) DeepCopy() *MaterialAttributesGit {
	if in == nil {
		return nil
	}
	out := new(MaterialAttributesGit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaterialAttributesHg) DeepCopyInto(out *MaterialAttributesHg) {
	*out = *in
	in.Filter.DeepCopyInto(&out.Filter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaterialAttributesHg.
func (in *MaterialAttributesHg) DeepCopy() *MaterialAttributesHg {
	if in == nil {
		return nil
	}
	out := new(MaterialAttributesHg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaterialAttributesP4) DeepCopyInto(out *MaterialAttributesP4) {
	*out = *in
	in.Filter.DeepCopyInto(&out.Filter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaterialAttributesP4.
func (in *MaterialAttributesP4) DeepCopy() *MaterialAttributesP4 {
	if in == nil {
		return nil
	}
	out := new(MaterialAttributesP4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaterialAttributesPackage) DeepCopyInto(out *MaterialAttributesPackage) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaterialAttributesPackage.
func (in *MaterialAttributesPackage) DeepCopy() *MaterialAttributesPackage {
	if in == nil {
		return nil
	}
	out := new(MaterialAttributesPackage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaterialAttributesPlugin) DeepCopyInto(out *MaterialAttributesPlugin) {
	*out = *in
	in.Filter.DeepCopyInto(&out.Filter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaterialAttributesPlugin.
func (in *MaterialAttributesPlugin) DeepCopy() *MaterialAttributesPlugin {
	if in == nil {
		return nil
	}
	out := new(MaterialAttributesPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaterialAttributesSvn) DeepCopyInto(out *MaterialAttributesSvn) {
	*out = *in
	in.Filter.DeepCopyInto(&out.Filter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaterialAttributesSvn.
func (in *MaterialAttributesSvn) DeepCopy() *MaterialAttributesSvn {
	if in == nil {
		return nil
	}
	out := new(MaterialAttributesSvn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaterialAttributesTfs) DeepCopyInto(out *MaterialAttributesTfs) {
	*out = *in
	in.Filter.DeepCopyInto(&out.Filter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaterialAttributesTfs.
func (in *MaterialAttributesTfs) DeepCopy() *MaterialAttributesTfs {
	if in == nil {
		return nil
	}
	out := new(MaterialAttributesTfs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Origin) DeepCopyInto(out *Origin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Origin.
func (in *Origin) DeepCopy() *Origin {
	if in == nil {
		return nil
	}
	out := new(Origin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parameter) DeepCopyInto(out *Parameter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parameter.
func (in *Parameter) DeepCopy() *Parameter {
	if in == nil {
		return nil
	}
	out := new(Parameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfig) DeepCopyInto(out *PipelineConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfig.
func (in *PipelineConfig) DeepCopy() *PipelineConfig {
	if in == nil {
		return nil
	}
	out := new(PipelineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigForProvider) DeepCopyInto(out *PipelineConfigForProvider) {
	*out = *in
	out.Origin = in.Origin
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]Parameter, len(*in))
		copy(*out, *in)
	}
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = make([]EnvironmentVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Materials != nil {
		in, out := &in.Materials, &out.Materials
		*out = make([]Material, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]Stage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.TrackingTool = in.TrackingTool
	out.Timer = in.Timer
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigForProvider.
func (in *PipelineConfigForProvider) DeepCopy() *PipelineConfigForProvider {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigForProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigList) DeepCopyInto(out *PipelineConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelineConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigList.
func (in *PipelineConfigList) DeepCopy() *PipelineConfigList {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigSpec) DeepCopyInto(out *PipelineConfigSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigSpec.
func (in *PipelineConfigSpec) DeepCopy() *PipelineConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigStatus) DeepCopyInto(out *PipelineConfigStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	if in.AtProvider != nil {
		in, out := &in.AtProvider, &out.AtProvider
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvironmentVariableHashes != nil {
		in, out := &in.EnvironmentVariableHashes, &out.EnvironmentVariableHashes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigStatus.
func (in *PipelineConfigStatus) DeepCopy() *PipelineConfigStatus {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Role) DeepCopyInto(out *Role) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Role.
func (in *Role) DeepCopy() *Role {
	if in == nil {
		return nil
	}
	out := new(Role)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Role) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleList) DeepCopyInto(out *RoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Role, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleList.
func (in *RoleList) DeepCopy() *RoleList {
	if in == nil {
		return nil
	}
	out := new(RoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleObservation) DeepCopyInto(out *RoleObservation) {
	*out = *in
	in.Attributes.DeepCopyInto(&out.Attributes)
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]RoleParametersPolicy, len(*in))
		copy(*out, *in)
	}
	out.Links = in.Links
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleObservation.
func (in *RoleObservation) DeepCopy() *RoleObservation {
	if in == nil {
		return nil
	}
	out := new(RoleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleParameters) DeepCopyInto(out *RoleParameters) {
	*out = *in
	in.Attributes.DeepCopyInto(&out.Attributes)
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]RoleParametersPolicy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleParameters.
func (in *RoleParameters) DeepCopy() *RoleParameters {
	if in == nil {
		return nil
	}
	out := new(RoleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleParametersAttributes) DeepCopyInto(out *RoleParametersAttributes) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]KeyValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleParametersAttributes.
func (in *RoleParametersAttributes) DeepCopy() *RoleParametersAttributes {
	if in == nil {
		return nil
	}
	out := new(RoleParametersAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleParametersPolicy) DeepCopyInto(out *RoleParametersPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleParametersPolicy.
func (in *RoleParametersPolicy) DeepCopy() *RoleParametersPolicy {
	if in == nil {
		return nil
	}
	out := new(RoleParametersPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleSpec) DeepCopyInto(out *RoleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleSpec.
func (in *RoleSpec) DeepCopy() *RoleSpec {
	if in == nil {
		return nil
	}
	out := new(RoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleStatus) DeepCopyInto(out *RoleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleStatus.
func (in *RoleStatus) DeepCopy() *RoleStatus {
	if in == nil {
		return nil
	}
	out := new(RoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Stage) DeepCopyInto(out *Stage) {
	*out = *in
	in.Approval.DeepCopyInto(&out.Approval)
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = make([]EnvironmentVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]Job, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Stage.
func (in *Stage) DeepCopy() *Stage {
	if in == nil {
		return nil
	}
	out := new(Stage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageApproval) DeepCopyInto(out *StageApproval) {
	*out = *in
	in.Authorization.DeepCopyInto(&out.Authorization)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageApproval.
func (in *StageApproval) DeepCopy() *StageApproval {
	if in == nil {
		return nil
	}
	out := new(StageApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageApprovalAuthorization) DeepCopyInto(out *StageApprovalAuthorization) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageApprovalAuthorization.
func (in *StageApprovalAuthorization) DeepCopy() *StageApprovalAuthorization {
	if in == nil {
		return nil
	}
	out := new(StageApprovalAuthorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Task) DeepCopyInto(out *Task) {
	*out = *in
	if in.ExecAttributes != nil {
		in, out := &in.ExecAttributes, &out.ExecAttributes
		*out = new(TaskExecAttributes)
		(*in).DeepCopyInto(*out)
	}
	if in.FetchAttributes != nil {
		in, out := &in.FetchAttributes, &out.FetchAttributes
		*out = new(TaskFetchAttributes)
		(*in).DeepCopyInto(*out)
	}
	if in.AntAttributes != nil {
		in, out := &in.AntAttributes, &out.AntAttributes
		*out = new(TaskAntAttributes)
		(*in).DeepCopyInto(*out)
	}
	if in.NantAttributes != nil {
		in, out := &in.NantAttributes, &out.NantAttributes
		*out = new(TaskNantAttributes)
		(*in).DeepCopyInto(*out)
	}
	if in.RakeAttributes != nil {
		in, out := &in.RakeAttributes, &out.RakeAttributes
		*out = new(TaskRakeAttributes)
		(*in).DeepCopyInto(*out)
	}
	if in.PluggableAttributes != nil {
		in, out := &in.PluggableAttributes, &out.PluggableAttributes
		*out = new(TaskPluggableAttributes)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Task.
func (in *Task) DeepCopy() *Task {
	if in == nil {
		return nil
	}
	out := new(Task)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskAntAttributes) DeepCopyInto(out *TaskAntAttributes) {
	*out = *in
	if in.RunIf != nil {
		in, out := &in.RunIf, &out.RunIf
		*out = make([]TaskAttributesRunIfTypes, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskAntAttributes.
func (in *TaskAntAttributes) DeepCopy() *TaskAntAttributes {
	if in == nil {
		return nil
	}
	out := new(TaskAntAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskAntAttributesWithCancel) DeepCopyInto(out *TaskAntAttributesWithCancel) {
	*out = *in
	in.TaskAntAttributes.DeepCopyInto(&out.TaskAntAttributes)
	if in.OnCancel != nil {
		in, out := &in.OnCancel, &out.OnCancel
		*out = new(Task)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskAntAttributesWithCancel.
func (in *TaskAntAttributesWithCancel) DeepCopy() *TaskAntAttributesWithCancel {
	if in == nil {
		return nil
	}
	out := new(TaskAntAttributesWithCancel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskExecAttributes) DeepCopyInto(out *TaskExecAttributes) {
	*out = *in
	if in.RunIf != nil {
		in, out := &in.RunIf, &out.RunIf
		*out = make([]TaskAttributesRunIfTypes, len(*in))
		copy(*out, *in)
	}
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkingDirectory != nil {
		in, out := &in.WorkingDirectory, &out.WorkingDirectory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskExecAttributes.
func (in *TaskExecAttributes) DeepCopy() *TaskExecAttributes {
	if in == nil {
		return nil
	}
	out := new(TaskExecAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskExecAttributesWithCancel) DeepCopyInto(out *TaskExecAttributesWithCancel) {
	*out = *in
	in.TaskExecAttributes.DeepCopyInto(&out.TaskExecAttributes)
	if in.OnCancel != nil {
		in, out := &in.OnCancel, &out.OnCancel
		*out = new(Task)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskExecAttributesWithCancel.
func (in *TaskExecAttributesWithCancel) DeepCopy() *TaskExecAttributesWithCancel {
	if in == nil {
		return nil
	}
	out := new(TaskExecAttributesWithCancel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskFetchAttributes) DeepCopyInto(out *TaskFetchAttributes) {
	*out = *in
	if in.RunIf != nil {
		in, out := &in.RunIf, &out.RunIf
		*out = make([]TaskAttributesRunIfTypes, len(*in))
		copy(*out, *in)
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = make([]KeyValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskFetchAttributes.
func (in *TaskFetchAttributes) DeepCopy() *TaskFetchAttributes {
	if in == nil {
		return nil
	}
	out := new(TaskFetchAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskFetchAttributesWithCancel) DeepCopyInto(out *TaskFetchAttributesWithCancel) {
	*out = *in
	in.TaskFetchAttributes.DeepCopyInto(&out.TaskFetchAttributes)
	if in.OnCancel != nil {
		in, out := &in.OnCancel, &out.OnCancel
		*out = new(Task)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskFetchAttributesWithCancel.
func (in *TaskFetchAttributesWithCancel) DeepCopy() *TaskFetchAttributesWithCancel {
	if in == nil {
		return nil
	}
	out := new(TaskFetchAttributesWithCancel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskNantAttributes) DeepCopyInto(out *TaskNantAttributes) {
	*out = *in
	if in.RunIf != nil {
		in, out := &in.RunIf, &out.RunIf
		*out = make([]TaskAttributesRunIfTypes, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskNantAttributes.
func (in *TaskNantAttributes) DeepCopy() *TaskNantAttributes {
	if in == nil {
		return nil
	}
	out := new(TaskNantAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskNantAttributesWithCancel) DeepCopyInto(out *TaskNantAttributesWithCancel) {
	*out = *in
	in.TaskNantAttributes.DeepCopyInto(&out.TaskNantAttributes)
	if in.OnCancel != nil {
		in, out := &in.OnCancel, &out.OnCancel
		*out = new(Task)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskNantAttributesWithCancel.
func (in *TaskNantAttributesWithCancel) DeepCopy() *TaskNantAttributesWithCancel {
	if in == nil {
		return nil
	}
	out := new(TaskNantAttributesWithCancel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskPluggableAttributes) DeepCopyInto(out *TaskPluggableAttributes) {
	*out = *in
	if in.RunIf != nil {
		in, out := &in.RunIf, &out.RunIf
		*out = make([]TaskAttributesRunIfTypes, len(*in))
		copy(*out, *in)
	}
	out.PluginConfiguration = in.PluginConfiguration
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = make([]KeyValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskPluggableAttributes.
func (in *TaskPluggableAttributes) DeepCopy() *TaskPluggableAttributes {
	if in == nil {
		return nil
	}
	out := new(TaskPluggableAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskPluggableAttributesPluginConfiguration) DeepCopyInto(out *TaskPluggableAttributesPluginConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskPluggableAttributesPluginConfiguration.
func (in *TaskPluggableAttributesPluginConfiguration) DeepCopy() *TaskPluggableAttributesPluginConfiguration {
	if in == nil {
		return nil
	}
	out := new(TaskPluggableAttributesPluginConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskPluggableAttributesWithCancel) DeepCopyInto(out *TaskPluggableAttributesWithCancel) {
	*out = *in
	in.TaskPluggableAttributes.DeepCopyInto(&out.TaskPluggableAttributes)
	if in.OnCancel != nil {
		in, out := &in.OnCancel, &out.OnCancel
		*out = new(Task)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskPluggableAttributesWithCancel.
func (in *TaskPluggableAttributesWithCancel) DeepCopy() *TaskPluggableAttributesWithCancel {
	if in == nil {
		return nil
	}
	out := new(TaskPluggableAttributesWithCancel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskRakeAttributes) DeepCopyInto(out *TaskRakeAttributes) {
	*out = *in
	if in.RunIf != nil {
		in, out := &in.RunIf, &out.RunIf
		*out = make([]TaskAttributesRunIfTypes, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskRakeAttributes.
func (in *TaskRakeAttributes) DeepCopy() *TaskRakeAttributes {
	if in == nil {
		return nil
	}
	out := new(TaskRakeAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskRakeAttributesWithCancel) DeepCopyInto(out *TaskRakeAttributesWithCancel) {
	*out = *in
	in.TaskRakeAttributes.DeepCopyInto(&out.TaskRakeAttributes)
	if in.OnCancel != nil {
		in, out := &in.OnCancel, &out.OnCancel
		*out = new(Task)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskRakeAttributesWithCancel.
func (in *TaskRakeAttributesWithCancel) DeepCopy() *TaskRakeAttributesWithCancel {
	if in == nil {
		return nil
	}
	out := new(TaskRakeAttributesWithCancel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskWithCancel) DeepCopyInto(out *TaskWithCancel) {
	*out = *in
	if in.ExecAttributes != nil {
		in, out := &in.ExecAttributes, &out.ExecAttributes
		*out = new(TaskExecAttributesWithCancel)
		(*in).DeepCopyInto(*out)
	}
	if in.FetchAttributes != nil {
		in, out := &in.FetchAttributes, &out.FetchAttributes
		*out = new(TaskFetchAttributesWithCancel)
		(*in).DeepCopyInto(*out)
	}
	if in.AntAttributes != nil {
		in, out := &in.AntAttributes, &out.AntAttributes
		*out = new(TaskAntAttributesWithCancel)
		(*in).DeepCopyInto(*out)
	}
	if in.NantAttributes != nil {
		in, out := &in.NantAttributes, &out.NantAttributes
		*out = new(TaskNantAttributesWithCancel)
		(*in).DeepCopyInto(*out)
	}
	if in.RakeAttributes != nil {
		in, out := &in.RakeAttributes, &out.RakeAttributes
		*out = new(TaskRakeAttributesWithCancel)
		(*in).DeepCopyInto(*out)
	}
	if in.PluggableAttributes != nil {
		in, out := &in.PluggableAttributes, &out.PluggableAttributes
		*out = new(TaskPluggableAttributesWithCancel)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskWithCancel.
func (in *TaskWithCancel) DeepCopy() *TaskWithCancel {
	if in == nil {
		return nil
	}
	out := new(TaskWithCancel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Timer) DeepCopyInto(out *Timer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Timer.
func (in *Timer) DeepCopy() *Timer {
	if in == nil {
		return nil
	}
	out := new(Timer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackingTool) DeepCopyInto(out *TrackingTool) {
	*out = *in
	out.Attributes = in.Attributes
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackingTool.
func (in *TrackingTool) DeepCopy() *TrackingTool {
	if in == nil {
		return nil
	}
	out := new(TrackingTool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackingToolAttributes) DeepCopyInto(out *TrackingToolAttributes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackingToolAttributes.
func (in *TrackingToolAttributes) DeepCopy() *TrackingToolAttributes {
	if in == nil {
		return nil
	}
	out := new(TrackingToolAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueSource) DeepCopyInto(out *ValueSource) {
	*out = *in
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(ConfigMapKeySelector)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueSource.
func (in *ValueSource) DeepCopy() *ValueSource {
	if in == nil {
		return nil
	}
	out := new(ValueSource)
	in.DeepCopyInto(out)
	return out
}
